In [1]:
from mlclasses_f3dasm import SimpleModel, LinearRegression
import tensorflow as tf
import f3dasm
import numpy as np

2022-12-20 12:44:45.257582: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-20 12:44:45.397697: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-12-20 12:44:46.158480: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.1/lib64:/usr/local/cuda-11.1/lib64
2022-12-20 12:44:46.158584: W ten

In [2]:
dimensionality = 3
seed = 42
design = f3dasm.make_nd_continuous_design(bounds=np.tile([-10.,10.], (dimensionality,1)), dimensionality=dimensionality)
sampler = f3dasm.sampling.LatinHypercube(design=design,seed=seed)
samples = sampler.get_samples(numsamples=200)
d = samples.get_input_data()
x = tf.convert_to_tensor(d)

2022-12-20 12:44:56.811717: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-12-20 12:44:56.811806: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (martin): /proc/driver/nvidia/version does not exist
2022-12-20 12:44:56.812944: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
def evaluate(X, *args, **kwargs):
    # d = X.shape[0]
    res = 0.5 * tf.reduce_sum(X**4 - 16 * X**2 + 5 * X, axis=1, keepdims=True)
    return res

In [4]:
m = SimpleModel(loss_function=evaluate)
m(x)

<tf.Tensor: shape=(200, 3), dtype=float32, numpy=
array([[ 2.40944433e+00, -2.56322837e+00, -8.73157692e+00],
       [ 1.63746130e+00,  5.89929628e+00, -3.90753055e+00],
       [ 5.79698801e+00,  1.27036583e+00,  2.61181641e+00],
       [-7.16890192e+00, -1.28599155e+00,  8.48766518e+00],
       [-2.09756851e+00,  7.66019762e-01,  3.07845652e-01],
       [ 3.58955240e+00, -7.35003591e-01,  9.46333981e+00],
       [ 4.07915783e+00,  4.96264845e-01, -2.17192268e+00],
       [ 5.95538521e+00,  5.31354621e-02,  2.13861036e+00],
       [ 4.31170654e+00,  5.52857113e+00,  1.24741733e+00],
       [ 4.97533798e+00, -9.69794178e+00, -5.67778921e+00],
       [ 9.88967896e+00, -9.71338272e+00,  2.21957922e+00],
       [-8.43374825e+00,  1.10460031e+00,  7.09327269e+00],
       [ 8.83505917e+00, -5.56623840e+00,  3.19307566e+00],
       [ 2.15456176e+00,  7.10452175e+00, -6.66200459e-01],
       [-6.84387207e+00,  1.99402297e+00, -5.42172015e-01],
       [-2.47560096e+00, -4.46792221e+00,  6.50777

In [5]:
n = LinearRegression()
n(x)

<tf.Tensor: shape=(200, 1), dtype=float32, numpy=
array([[ 0.06242011],
       [ 0.02660076],
       [ 0.04384487],
       [-0.10371774],
       [-0.02230007],
       [-0.00435602],
       [ 0.04807703],
       [ 0.04852776],
       [ 0.03114832],
       [ 0.08121529],
       [ 0.09555453],
       [-0.11237168],
       [ 0.07730563],
       [ 0.01682996],
       [-0.06577961],
       [-0.04699396],
       [ 0.01553353],
       [ 0.00086941],
       [-0.10758946],
       [-0.04471077],
       [ 0.03516158],
       [ 0.06333741],
       [-0.03303552],
       [ 0.04633944],
       [ 0.04340557],
       [ 0.12493666],
       [-0.05174307],
       [-0.07313289],
       [ 0.00545602],
       [-0.06680852],
       [ 0.08946388],
       [ 0.05681073],
       [-0.05432711],
       [ 0.0657143 ],
       [ 0.00086946],
       [-0.03594375],
       [-0.00156403],
       [-0.02616873],
       [ 0.0815361 ],
       [ 0.10199411],
       [ 0.06735006],
       [ 0.10374084],
       [ 0.00030813],
    

In [6]:
def f:

In [7]:
m = SimpleModel(loss_function=None)

In [8]:
m.model.trainable_variables

ValueError: Weights for model sequential_3 have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`.